import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navigation from '../components/Navigation'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Persionalized New application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <Navigation></Navigation>
      </main>
    </div>
  )
}
